In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
data = {
    "Tenure": [12,24,3,6,36,48,2,8,18,30],
    "MonthlyCharges": [50,45,80,75,40,35,90,70,55,50],
    "SupportCalls": [1,0,5,4,0,0,6,3,1,1],
    "Churn": [0,0,1,1,0,0,1,1,0,0]
}

df = pd.DataFrame(data)

df.head()

   Tenure  MonthlyCharges  SupportCalls  Churn
0      12              50             1      0
1      24              45             0      0
2       3              80             5      1
3       6              75             4      1
4      36              40             0      0

In [3]:
df.describe()

          Tenure  MonthlyCharges  SupportCalls      Churn
count  10.000000       10.000000     10.000000  10.000000
mean   18.700000       59.000000      2.100000   0.400000
std    15.492292       18.529256      2.233582   0.516398
min     2.000000       35.000000      0.000000   0.000000
25%     6.500000       46.250000      0.250000   0.000000
50%    15.000000       52.500000      1.000000   0.000000
75%    28.500000       73.750000      3.750000   1.000000
max    48.000000       90.000000      6.000000   1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Tenure          10 non-null     int64
 1   MonthlyCharges  10 non-null     int64
 2   SupportCalls    10 non-null     int64
 3   Churn           10 non-null     int64
dtypes: int64(4)
memory usage: 452.0 bytes

In [5]:
X = df[[
    "Tenure",
    "MonthlyCharges",
    "SupportCalls"
]]

y = df["Churn"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [8]:
predictions = model.predict(X_test)

In [9]:
accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [10]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
)

          Feature  Importance
0          Tenure    0.363636
1  MonthlyCharges    0.363636
2    SupportCalls    0.272727

In [11]:
new_customer = [[4, 85, 5]]

prediction = model.predict(new_customer)

if prediction[0] == 1:
    print("Customer likely to churn")
else:
    print("Customer likely to stay")

Customer likely to churn

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(